apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce
  labels:
    app: cloud-config
spec:
  selector:
    app: cloud-config
  ports:
    - protocol: TCP
      port: 9296
      targetPort: 9296
  type: ClusterIP 